In [53]:
import numpy as np
import pandas as pd
import nltk
import sys

In [94]:
corpus_xk = pd.read_excel("corpus_xk.xlsx")

In [3]:
corpus_xk

,Interviewee,Task,Sentence,Data Related,Table,Note
0,WJC,1,What is the popularity of Arkansas on July 1st...,"popularity, Arkansas, July 1st 2002",co-est2002-01-05,NaN
1,WJC,1,Where is Harvard University?,Harvard University,top-50-us-universities,where 表示 location
2,WJC,1,How many faculties are there in Harvard Univer...,"faculties, Harvard Universtiy",top-50-us-universities,NaN
3,WJC,1,What is the type of Harvard University?,"Harvard University, type",top-50-us-universities,NaN
4,WJC,2,which county has more than 30000 popularity?,"county, 30000 popularity",co-est2002-01-05,NaN
...,...,...,...,...,...,...
485,ZJH,6,Can you tell me what the range of students' sc...,"students' score, CW2",NaN,NaN
486,ZJH,7,Does this table show anything about the distri...,F grade students,NaN,NaN
487,ZJH,8,Which student didn't do as well as expected in...,"student, final exam",NaN,NaN
488,ZJH,9,Is there any obvious clustering of students' w...,students' weight,NaN,NaN
489,ZJH,10,Does a student's grade have anything to do wit...,"student's grade, city",NaN,NaN

In [4]:
corpus_xk.dtypes

Interviewee     object
Task            object
Sentence        object
Data Related    object
Table           object
Note            object
dtype: object

In [15]:
corpus_xk.iloc[0].sentence, type(corpus_xk.iloc[0]),corpus_xk.iloc[0].task,type(corpus_xk.iloc[0].task)

('What is the popularity of Arkansas on July 1st 2002?',
 pandas.core.series.Series,
 1,
 int)

In [18]:
corpus_xk[(corpus_xk.Task == '1') | (corpus_xk.Task == 1) | corpus_xk.Task.str.contains('1,', case=False, na=False)].loc[:,["Task","Sentence"]]

    Task                                           Sentence
0      1  What is the popularity of Arkansas on July 1st...
1      1                       Where is Harvard University?
2      1  How many faculties are there in Harvard Univer...
3      1            What is the type of Harvard University?
42     1             What is the happiness rank of Iceland?
43     1   How many dimensions to describe happiness score?
44     1            How many students in the grade records?
45     1               Show me Kibo Mcgee's mid-term score.
83     1                  What is the revenue of "Titanic"?
84     1   How many goals does Liverpool score in the game?
85     1          Find the score of course A for student B.
86     1  How long would it take from location A to loca...
128    1                What region does Iceland belong to?
129    1          Which country is the 15th most happy one?
130    1  How would people in Iceland rate theirs happin...
131    1  Which country is the next target, if Iceland w...
155    1    Which publisher published The Queen of Nothing?
156    1              Find me books written by Brian Tracy.
157    1  What language is The Art of Super Mario Odysse...
158    1              Is Barbara Allan's book highly rated?
160    1                      How long is Beautiful People?
161    1             What's the length of Beautiful People?
162    1             What pop songs has Sam Simth released?
163    1     Could you give me some pop songs by Sam Simth?
244    1  what is the current version of "Coloring book ...
245    1  tell me the size of "Kids Paint Free - Drawing...
260    1                            display a random reason
261    1      What kind of jobs does students' mother have?
270    1  How many likes does the video titled "PLUSH - ...
271    1  Does the video "PLUSH - Bad Unboxing Fan Mail"...
272    1  What time was "PLUSH - Bad Unboxing Fan Mail" ...
273    1  Since when has "PLUSH - Bad Unboxing Fan Mail"...
274    1  How many users liked the video "PLUSH - Bad Un...
275    1  What is the date that "PLUSH - Bad Unboxing Fa...
276    1  Tell me the number of likes that "PLUSH - Bad ...
277    1  What channel does "PLUSH - Bad Unboxing Fan Ma...
278    1  Which channel published the video "PLUSH - Bad...
279    1  Describe the video "PLUSH - Bad Unboxing Fan M...
324    1  How many times has "Coloring book moana" been ...
325    1             Is "Coloring book moana" free or paid?
345    1   Where was the movie Transformers Prime produced?
346    1  I would like to know the rating of the movie T...
366    1  How many people from Albania at the age of 15-...
367    1                What is the GDP of Albania in 1987?
387    1  What is the number of undergraduate students o...
388    1  What is the percentage of underguaduate studen...
389    1  What are the income of undergraduates and post...
390    1  Where was the match hold between England and W...
391    1  Find the place where the match hold between En...
453    1  I would like to inquire of you about the value...
454    1                    How many people live in Hawaii?
455    1                 How many people smoke in Maryland?
479    1  I am dying to know Lucas Mcgee's Mid-term exam...

In [19]:
task1 = dict(corpus_xk[(corpus_xk.Task == '1') | (corpus_xk.Task == 1) | corpus_xk.Task.str.contains('1,', case=False, na=False)].Sentence)

In [95]:
tasks_sentences = []
tasks_len = []
for i in range(1,11):
    # tasks_sentences.append([i,str(i),str(i)+','])
    tasks_sentences.append(list(corpus_xk[(corpus_xk.Task == i) | (corpus_xk.Task == str(i)) | corpus_xk.Task.str.contains(str(i) + ',', case=False, na=False)].Sentence))
    # print(len(tasks_sentences[i-1]))
    tasks_len.append(len(tasks_sentences[i-1]))
    
sum(tasks_len)

490

In [96]:
tasks_sentences[0]

['What is the popularity of Arkansas on July 1st 2002?',
 'Where is Harvard University?',
 'How many faculties are there in Harvard Universtiy?',
 'What is the type of Harvard University?',
 'What is the happiness rank of Iceland?',
 'How many dimensions to describe happiness score?',
 'How many students in the grade records?',
 "Show me Kibo Mcgee's mid-term score.",
 'What is the revenue of "Titanic"?',
 'How many goals does Liverpool score in the game?',
 'Find the score of course A for student B.',
 'How long would it take from location A to location B?',
 'What region does Iceland belong to?',
 'Which country is the 15th most happy one?',
 'How would people in Iceland rate theirs happiness?',
 'Which country is the next target, if Iceland want to enhance the happiness score?',
 'Which publisher published The Queen of Nothing?',
 'Find me books written by Brian Tracy.',
 'What language is The Art of Super Mario Odyssey written in?',
 "Is Barbara Allan's book highly rated?",
 'How long is Beautiful People?',
 "What's the length of Beautiful People?",
 'What pop songs has Sam Simth released?',
 'Could you give me some pop songs by Sam Simth?',
 'what is the current version of "Coloring book moana"',
 'tell me the size of "Kids Paint Free - Drawing Fun"',
 'display a random reason',
 "What kind of jobs does students' mother have?",
 'How many likes does the video titled "PLUSH - Bad Unboxing Fan Mail" have?',
 'Does the video "PLUSH - Bad Unboxing Fan Mail" allow comments?',
 'What time was "PLUSH - Bad Unboxing Fan Mail" published?',
 'Since when has "PLUSH - Bad Unboxing Fan Mail" been trending?',
 'How many users liked the video "PLUSH - Bad Unboxing Fan Mail"?',
 'What is the date that "PLUSH - Bad Unboxing Fan Mail" became trending?',
 'Tell me the number of likes that "PLUSH - Bad Unboxing Fan Mail" receives',
 'What channel does "PLUSH - Bad Unboxing Fan Mail" belong to?',
 'Which channel published the video "PLUSH - Bad Unboxing Fan Mail"?',
 'Describe the video "PLUSH - Bad Unboxing Fan Mail".',
 'How many times has "Coloring book moana" been installed?',
 'Is "Coloring book moana" free or paid?',
 'Where was the movie Transformers Prime produced?',
 'I would like to know the rating of the movie Transformers Prime.',
 'How many people from Albania at the age of 15-24 years suicide in 1987?',
 'What is the GDP of Albania in 1987?',
 'What is the number of undergraduate students of United Kingdom in 2001?',
 'What is the percentage of underguaduate students of all countries in 2001?',
 'What are the income of undergraduates and postgraduates of United Kingdom in 2001 respectively?',
 'Where was the match hold between England and Wales on 1879-01-08?',
 'Find the place where the match hold between England and Walse on 1879-01-08.',
 'I would like to inquire of you about the value of Percentage Attempted To Quit Smoking in Ohio.',
 'How many people live in Hawaii?',
 'How many people smoke in Maryland?',
 "I am dying to know Lucas Mcgee's Mid-term exams result."]

In [58]:
tasks_sentences[0]

{0: 'What is the popularity of Arkansas on July 1st 2002?',
 1: 'Where is Harvard University?',
 2: 'How many faculties are there in Harvard Universtiy?',
 3: 'What is the type of Harvard University?',
 42: 'What is the happiness rank of Iceland?',
 43: 'How many dimensions to describe happiness score?',
 44: 'How many students in the grade records?',
 45: "Show me Kibo Mcgee's mid-term score.",
 83: 'What is the revenue of "Titanic"?',
 84: 'How many goals does Liverpool score in the game?',
 85: 'Find the score of course A for student B.',
 86: 'How long would it take from location A to location B?',
 128: 'What region does Iceland belong to?',
 129: 'Which country is the 15th most happy one?',
 130: 'How would people in Iceland rate theirs happiness?',
 131: 'Which country is the next target, if Iceland want to enhance the happiness score?',
 155: 'Which publisher published The Queen of Nothing?',
 156: 'Find me books written by Brian Tracy.',
 157: 'What language is The Art of Super Mario Odyssey written in?',
 158: "Is Barbara Allan's book highly rated?",
 160: 'How long is Beautiful People?',
 161: "What's the length of Beautiful People?",
 162: 'What pop songs has Sam Simth released?',
 163: 'Could you give me some pop songs by Sam Simth?',
 244: 'what is the current version of "Coloring book moana"',
 245: 'tell me the size of "Kids Paint Free - Drawing Fun"',
 260: 'display a random reason',
 261: "What kind of jobs does students' mother have?",
 270: 'How many likes does the video titled "PLUSH - Bad Unboxing Fan Mail" have?',
 271: 'Does the video "PLUSH - Bad Unboxing Fan Mail" allow comments?',
 272: 'What time was "PLUSH - Bad Unboxing Fan Mail" published?',
 273: 'Since when has "PLUSH - Bad Unboxing Fan Mail" been trending?',
 274: 'How many users liked the video "PLUSH - Bad Unboxing Fan Mail"?',
 275: 'What is the date that "PLUSH - Bad Unboxing Fan Mail" became trending?',
 276: 'Tell me the number of likes that "PLUSH - Bad Unboxing Fan Mail" receives',
 277: 'What channel does "PLUSH - Bad Unboxing Fan Mail" belong to?',
 278: 'Which channel published the video "PLUSH - Bad Unboxing Fan Mail"?',
 279: 'Describe the video "PLUSH - Bad Unboxing Fan Mail".',
 324: 'How many times has "Coloring book moana" been installed?',
 325: 'Is "Coloring book moana" free or paid?',
 345: 'Where was the movie Transformers Prime produced?',
 346: 'I would like to know the rating of the movie Transformers Prime.',
 366: 'How many people from Albania at the age of 15-24 years suicide in 1987?',
 367: 'What is the GDP of Albania in 1987?',
 387: 'What is the number of undergraduate students of United Kingdom in 2001?',
 388: 'What is the percentage of underguaduate students of all countries in 2001?',
 389: 'What are the income of undergraduates and postgraduates of United Kingdom in 2001 respectively?',
 390: 'Where was the match hold between England and Wales on 1879-01-08?',
 391: 'Find the place where the match hold between England and Walse on 1879-01-08.',
 453: 'I would like to inquire of you about the value of Percentage Attempted To Quit Smoking in Ohio.',
 454: 'How many people live in Hawaii?',
 455: 'How many people smoke in Maryland?',
 479: "I am dying to know Lucas Mcgee's Mid-term exams result."}

In [31]:
tasks_sentences[0][0].split(' ')

['What',
 'is',
 'the',
 'popularity',
 'of',
 'Arkansas',
 'on',
 'July',
 '1st',
 '2002?']

In [42]:
sss = " sdf sd   df "
sss.split()

['sdf', 'sd', 'df']

In [43]:
def task_sentences_len(task_sentences):
    ts_len = []
    for sentence in task_sentences.values():
        ts_len.append(len(sentence.split()))  # sentence.strip().split(' ')
        
    return ts_len

In [50]:
for i in nltk.ngrams(tasks_sentences[0][0],3):
    print(i)

('W', 'h', 'a')
('h', 'a', 't')
('a', 't', ' ')
('t', ' ', 'i')
(' ', 'i', 's')
('i', 's', ' ')
('s', ' ', 't')
(' ', 't', 'h')
('t', 'h', 'e')
('h', 'e', ' ')
('e', ' ', 'p')
(' ', 'p', 'o')
('p', 'o', 'p')
('o', 'p', 'u')
('p', 'u', 'l')
('u', 'l', 'a')
('l', 'a', 'r')
('a', 'r', 'i')
('r', 'i', 't')
('i', 't', 'y')
('t', 'y', ' ')
('y', ' ', 'o')
(' ', 'o', 'f')
('o', 'f', ' ')
('f', ' ', 'A')
(' ', 'A', 'r')
('A', 'r', 'k')
('r', 'k', 'a')
('k', 'a', 'n')
('a', 'n', 's')
('n', 's', 'a')
('s', 'a', 's')
('a', 's', ' ')
('s', ' ', 'o')
(' ', 'o', 'n')
('o', 'n', ' ')
('n', ' ', 'J')
(' ', 'J', 'u')
('J', 'u', 'l')
('u', 'l', 'y')
('l', 'y', ' ')
('y', ' ', '1')
(' ', '1', 's')
('1', 's', 't')
('s', 't', ' ')
('t', ' ', '2')
(' ', '2', '0')
('2', '0', '0')
('0', '0', '2')
('0', '2', '?')

In [92]:
class NGram(object):

    def __init__(self):
        # n is the order of n-gram language model
        self.unigram = {}
        self.bigram = {}
        self.trigram = {}
        self.sentence_len = []

    # scan a sentence, extract the ngram and update their
    # frequence.
    #
    # @param    sentence    list{str}
    # @return   none
    def scan(self, sentences):
        fip = ""
        # file your code here
        for sentence in sentences.values():
            self.sentence_len.append(len(sentence.split()))  # sentence.strip().split(' ')
            self.ngram(sentence.split())
        # unigram
        try:
            fip = open("uni", "w", encoding='utf-8')
        except:
            print(sys.stderr, "failed to open data.uni")
        tmp = zip(self.unigram.values(),self.unigram.keys())
        for i in sorted(tmp,reverse=True):
            fip.write("%s %d\n" % (i[1], i[0]))
            
        # bigram
        try:
            fip = open("bi", "w", encoding='utf-8')
        except:
            print(sys.stderr, "failed to open data.bi")
        tmp = zip(self.bigram.values(),self.bigram.keys())
        for i in sorted(tmp,reverse=True):
            fip.write("%s %d\n" % (i[1], i[0]))
            
        # bigram
        try:
            fip = open("tri", "w", encoding='utf-8')
        except:
            print(sys.stderr, "failed to open data.tri")
        tmp = zip(self.trigram.values(),self.trigram.keys())
        for i in sorted(tmp,reverse=True):
            fip.write("%s %d\n" % (i[1], i[0]))
        
        try:
            fip = open("len", "w", encoding='utf-8')
        except:
            print(sys.stderr, "failed to open data.len")
        fip.write("Sentences Num: %d\n" % (len(self.sentence_len)))
        for i in self.sentence_len:
            fip.write("%d, " % (i))


    # caluclate the ngram of the words
    #
    # @param    words       list{str}
    # @return   none
    def ngram(self, words):
        wlen = len(words)
                  
        for i in range(wlen):
            word = words[i]
                  
            if word not in self.unigram:
                self.unigram[word] = 1
            else:
                self.unigram[word] = self.unigram[word] + 1
            
            if i < (wlen - 1):
                bi_words = ' '.join([word, words[i+1]])
                if bi_words not in self.bigram:
                    self.bigram[bi_words] = 1
                else:
                    self.bigram[bi_words] = self.bigram[bi_words] + 1
                
                if i < (wlen - 2):
                    tri_words = ' '.join([word, words[i+1], words[i+2]])
                    if tri_words not in self.trigram:
                        self.trigram[tri_words] = 1
                    else:
                        self.trigram[tri_words] = self.trigram[tri_words] + 1

In [93]:
ngram = NGram()
ngram.scan(tasks_sentences[0])

In [31]:
corpus_xk[corpus_xk["task"].str.contains('1', case=False, na=False)]

,interviewee,task,sentence,data related,table,note
44,ZKJ,1,What is the happiness rank of Iceland?,"happiness rank, Iceland",World Happiness Report 2015,NaN
45,ZKJ,1,How many dimensions to describe happiness score?,"happiness score, dimensions",World Happiness Report 2015,NaN
46,ZKJ,1,How many students in the grade records?,"students, grade",grade-records,NaN
47,ZKJ,1,Show me Kibo Mcgee's mid-term score.,"Kibo Mcgee, mid-term score",grade-records,NaN
81,ZKJ,10,Can we infer that higher freedom lead to highe...,"freedom, happiness",World Happiness Report 2015,NaN
82,ZKJ,10,Is the countries has higher trust score get th...,"trust score, happiness score",World Happiness Report 2015,NaN
83,ZKJ,10,Who get the greatest progression?,progression,grade-records,"Who 指的是学生, progression指的是分数提高很多"
84,ZKJ,10,Is any teachers lead to the greater grades?,"teachers, grades",grade-records,NaN
87,XX,1,"What is the revenue of ""Titanic""?","revenue, Titanic",NaN,NaN
88,XX,1,How many goals does Liverpool score in the game?,"goals, Liverpool, game",NaN,NaN
89,XX,1,Find the score of course A for student B.,"score, course A, student B",NaN,NaN
90,XX,1,How long would it take from location A to loca...,"location A, location B",NaN,NaN
115,XX,10,What is the correlation between the release ye...,"release year, revenue",NaN,NaN
116,XX,10,Are the release year and the revenue positivel...,"release year, revenue",NaN,NaN
117,XX,10,Does a higher A mean a larger B?,NaN,NaN,NaN
118,XX,10,Is it true that young students are more likely...,"students, wechat",NaN,young students：涉及到ages属性，一般来说ages<20，或者定义为：统计所...
130,WJ,10,Find out the relationship between happiness sc...,happiness score,World Happiness Report 2015,NaN
131,WJ,10,How economy or something else affect happiness...,"economy, happiness score",World Happiness Report 2015,NaN
458,ZJH,10,Does life expectancy have some relation with t...,"life expectancy, smokers",NaN,the percentage of smokers = 吸烟的人数/总人数
460,ZJH,10,Can you tell me the tendency of the number of ...,"vehicles, Japan, Korea, 2000, 2010",NaN,NaN

In [80]:
from random import randint
d={x:randint(60,99) for x in "abcdefgab"}   # {'a': 62, 'b': 97, 'c': 87, 'd': 68, 'e': 91, 'f': 76, 'g': 88}

In [81]:
d

{'a': 92, 'b': 88, 'c': 98, 'd': 66, 'e': 77, 'f': 74, 'g': 93}

In [83]:
z=[(62, 'asdf'), (62, 'aa'), (87, 'c'), (68, 'd'), (91, 'e'), (76, 'f'), (88, 'g')]
zz = sorted(z)
# zz.reverse()
print(zz)

[(62, 'aa'), (62, 'asdf'), (68, 'd'), (76, 'f'), (87, 'c'), (88, 'g'), (91, 'e')]

In [67]:
aa = [(98, 'f'), (96, 'c'), (95, 'd'), (93, 'e'), (84, 'a'), (72, 'g'), (63, 'b')]

In [68]:
aa.reverse()

In [69]:
aa

[(63, 'b'), (72, 'g'), (84, 'a'), (93, 'e'), (95, 'd'), (96, 'c'), (98, 'f')]